CREATE TABLE COMPANY(
    COM_ID CHAR(5) PRIMARY KEY,
    COM_NAME VARCHAR2(20),
    COM_CATEGORY VARCHAR2(20),
    COM_ADDR VARCHAR2(100),
    COM_PIC_FNAME VARCHAR2(20),
    COM_PIC_LNAME VARCHAR2(20),
    COM_PIC_TITLE VARCHAR2(20),
    COM_PHONE VARCHAR2(13),
    COM_EMAIL VARCHAR2(20)
);

--COMPANY table created