CREATE OR REPLACE FUNCTION AUTHENTICATE_ACC_LOGIN (
    P_EMPLOYEE_ID IN CHAR,
    P_EMPLOYEE_PW IN VARCHAR2
) RETURN BOOLEAN
IS
    L_EMP_ID CHAR(8) := LOWER(P_EMPLOYEE_ID);
    L_EMP_PW VARCHAR2(12) := P_EMPLOYEE_PW;
    L_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO L_COUNT
    FROM EMPLOYEE
    WHERE EMP_ID = L_EMP_ID
        AND EMP_PW = L_EMP_PW;
    IF L_COUNT = 0 THEN
        RETURN FALSE;
    END IF;
EXCEPTION
    WHEN OTHERS THEN RETURN FALSE;
END AUTHENTICATE_ACC_LOGIN;
/