CREATE OR REPLACE FUNCTION AUTHENTICATE_ACC_LOGIN (
    P_USERNAME IN VARCHAR2,
    P_PASSWORD IN VARCHAR2
) RETURN BOOLEAN
IS
    L_EMP_EMAIL VARCHAR2(30) := LOWER(P_USERNAME);
    L_EMP_PW VARCHAR2(12) := P_PASSWORD;
    L_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO L_COUNT
    FROM EMPLOYEE
    WHERE EMP_EMAIL = L_EMP_EMAIL
        AND EMP_PW = L_EMP_PW;
    IF L_COUNT = 0 THEN RETURN FALSE;
    ELSE RETURN TRUE;
    END IF;
EXCEPTION
    WHEN OTHERS THEN RETURN FALSE;
END AUTHENTICATE_ACC_LOGIN;
/