--INSERT DATA INTO CITY--
INSERT INTO CITY VALUES(50000,'Kuala Lumpur','Wilayah Persekutuan');
INSERT INTO CITY VALUES(40100,'Shah Alam','Selangor');
INSERT INTO CITY VALUES(80000,'Johor Bahru','Johor');
INSERT INTO CITY VALUES(11900,'Bayan Lepas','Penang');
INSERT INTO CITY VALUES(10300,'George Town','Penang');
INSERT INTO CITY VALUES(93300,'Kuching','Sarawak');
INSERT INTO CITY VALUES(98000,'Miri','Sarawak');
INSERT INTO CITY VALUES(25000,'Kuantan','Pahang');
INSERT INTO CITY VALUES(30000,'Ipoh','Perak');
INSERT INTO CITY VALUES(01000,'Kangar','Perlis');
INSERT INTO CITY VALUES(15200,'Kota Bharu','Kelantan');


--SEQUENCE FOR WAREHOUSE ID--
CREATE SEQUENCE WAREHOUSE_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

--SEQUENCE FOR EMPLOYEE ID--
CREATE SEQUENCE EMPLOYEE_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--PROCEDURE TO INSERT WAREHOUSE DATA--
CREATE OR REPLACE PROCEDURE INSERT_WAREHOUSE(
    WHS_NAME IN VARCHAR2,
    WHS_ADDR IN VARCHAR2,
    WHS_OPEN IN TIMESTAMP,
    WHS_CLOSE IN TIMESTAMP,
    POSTCODE IN NUMBER
)
AS
    V_WHS_ID CHAR(5);
BEGIN
    SELECT 'W' || LPAD(WAREHOUSE_ID_SEQ.NEXTVAL, 4, '0') INTO V_WHS_ID FROM DUAL;

    INSERT INTO WAREHOUSE(WHS_ID, WHS_NAME, WHS_ADDR, WHS_OPEN, WHS_CLOSE, POSTCODE)
    VALUES(V_WHS_ID, WHS_NAME, WHS_ADDR, WHS_OPEN, WHS_CLOSE, POSTCODE);
END;

--INSERT WAREHOUSE DATA--

--TRIGGER TO CHECK TIN number IGxxxxxxxxx--
CREATE OR REPLACE TRIGGER TIN_CHECK
BEFORE INSERT OR UPDATE OF EMP_TIN ON EMPLOYEE
FOR EACH ROW
BEGIN
    IF NOT REGEXP_LIKE(:NEW.EMP_TIN, 'IG\d{9,11}$') THEN
        RAISE_APPLICATION_ERROR(-20001, 'TIN number must start with IG followed by 9 to 11 digits');
    END IF;
END;
CREATE OR REPLACE PROCEDURE INSERT_EMPLOYEE(
    EMP_PW IN VARCHAR,
    EMP_TIN IN VARCHAR,
    EMP_IC IN CHAR,
    EMP_FNAME IN VARCHAR2,
    EMP_LNAME IN VARCHAR2,
    EMP_ROLE IN VARCHAR2,
    EMP_TITLE IN VARCHAR2,
    EMP_BDATE IN DATE,
    EMP_PHONE IN VARCHAR2,
    EMP_EMAIL IN VARCHAR2,
    WHS_ID IN CHAR
)
AS
    V_EMP_ID CHAR(5);
BEGIN
    SELECT 'E' || LPAD(EMPLOYEE_ID_SEQ.NEXTVAL, 4, '0') INTO V_EMP_ID FROM DUAL;

    INSERT INTO EMPLOYEE(EMP_ID, EMP_PW, EMP_TIN, EMP_IC, EMP_FNAME, EMP_LNAME, EMP_ROLE, EMP_TITLE, EMP_BDATE, EMP_PHONE, EMP_EMAIL, WHS_ID)
    VALUES(V_EMP_ID, EMP_PW, EMP_TIN, EMP_IC, EMP_FNAME, EMP_LNAME, EMP_ROLE, EMP_TITLE, EMP_BDATE, EMP_PHONE, EMP_EMAIL, WHS_ID);
END;