CREATE TABLE LOGISTIC_PROVIDER(
    LOG_ID CHAR(6) PRIMARY KEY,
    LOG_NAME VARCHAR2(20) NOT NULL,
    LOG_PIC_FNAME VARCHAR2(20) NOT NULL,
    LOG_PIC_LNAME VARCHAR2(20) NOT NULL,
    LOG_PIC_TITLE VARCHAR2(10) NOT NULL,
    LOG_PHONE VARCHAR2(13) NOT NULL,
    LOG_EMAIL VARCHAR2(20) NOT NULL,
    LOG_OPEN TIMESTAMP NOT NULL,
    LOG_CLOSE TIMESTAMP NOT NULL
);

CREATE TABLE INVOICE(
    INV_ID CHAR(6) PRIMARY KEY,
    INV_DATE DATE NOT NULL,
    INV_DESC VARCHAR2(100),
    INV_REMARKS VARCHAR2(100),
    INV_AMOUNT NUMBER(10,2) NOT NULL,
    INV_PAY_TERM NUMBER(3,0) NOT NULL,
    ORD_ID CHAR(6) NOT NULL,
    FOREIGN KEY (ORD_ID) REFERENCES ORDERS(ORD_ID)
);

CREATE TABLE PAYMENT(
    PAY_ID CHAR(6) PRIMARY KEY,
    PAY_DATE DATE NOT NULL,
    PAY_METHOD VARCHAR2(4) NOT NULL,
    INV_ID CHAR(6) NOT NULL,
    FOREIGN KEY (INV_ID) REFERENCES INVOICE(INV_ID)
);

CREATE TABLE DRIVER (
    DRIVER_ID CHAR(6) PRIMARY KEY,
    DRIVER_LISENCE_NO CHAR(10) NOT NULL,
    DRIVER_FNAME VARCHAR2(20) NOT NULL,
    DRIVER_LNAME VARCHAR2(20) NOT NULL,
    DRIVER_TITLE VARCHAR2(10) NOT NULL,
    DRIVER_BDATE DATE NOT NULL,
    DRIVER_PHONE VARCHAR2(13) NOT NULL,
    DRIVER_AVAILABILITY CHAR(1) NOT NULL,
    LOG_ID CHAR(6) NOT NULL,
    FOREIGN KEY (LOG_ID) REFERENCES LOGISTIC_PROVIDER(LOG_ID)
);


CREATE TABLE FEEDBACK(
    FBK_ID CHAR(8) PRIMARY KEY,
    FBK_RATING NUMBER(1,0) NOT NULL,
    FBK_DESC VARCHAR2(100),
    FBK_DATE DATE NOT NULL,
    ORD_ID CHAR(6) NOT NULL,
    FOREIGN KEY (ORD_ID) REFERENCES ORDERS(ORD_ID)
);