--RECYCLED_ITEM
CREATE TABLE RECYCLED_ITEM(
    RITEM_ID CHAR(6) PRIMARY KEY,
    RITEM_CONDITION NUMBER(1) NOT NULL,
    RITEM_QC_DATE DATE NOT NULL,
    RITEM_QTY NUMBER(10,2) NOT NULL,
    RORD_ID CHAR(6) NOT NULL,
    PROD_ID CHAR(6) NOT NULL,
    FOREIGN KEY (RORD_ID) REFERENCES RECYCLE_ORDER(RORD_ID),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

--RETURNED HISTORY TABLE--

CREATE TABLE RETURNED_HISTORY(
    RHS_ID CHAR(6) PRIMARY KEY,
    RETURNED_DATE DATE NOT NULL,
    RHIS_STAT CHAR(3) NOT NULL,
    EMP_ID CHAR(5) NOT NULL,
    RITEM_ID CHAR(6) NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
    FOREIGN KEY (RTEM_ID) REFERENCES RECYCLED_ITEM(RITEM_ID)
);

--RECYCLE_ORDER--

CREATE TABLE RECYCLE_ORDER(
    RORD_ID CHAR(6) PRIMARY KEY,
    RORD_DEALING_DATE DATE NOT NULL,
    RORD_DELIVERY_DATE DATE NOT NULL,
    RORD_STATE CHAR(3) NOT NULL,
    COM_ID CHAR(5) NOT NULL,
    FOREIGN KEY (COM_ID) REFERENCES COMPANY(COM_ID)
);

--RECYCLE_TRANSACTION--

CREATE TABLE RECYCLE_TRANSACTION(
    RTRANS_ID CHAR(6) PRIMARY KEY,
    RTRANS_AMOUNT NUMBER(10,2) NOT NULL,
    RTRANS_PAY_METHOD VARCHAR(4) NOT NULL,
    RTRANS_DATE DATE NOT NULL,
    RORD_ID CHAR(6) NOT NULL,
    FOREIGN KEY (RORD_ID) REFERENCES RECYCLE_ORDER(RODR_ID)
);


