CREATE TABLE CITY(
    POSTCODE NUMBER(5) PRIMARY KEY,
    CITY_NAME VARCHAR2(20) NOT NULL,
    CITY_STATE VARCHAR2(20) NOT NULL
);

CREATE TABLE WAREHOUSE(
    WHS_ID CHAR(5) PRIMARY KEY,
    WHS_NAME VARCHAR2(20) NOT NULL,
    WHS_ADDR VARCHAR2(100) NOT NULL,
    WHS_OPEN TIMESTAMP NOT NULL,
    WHS_CLOSE TIMESTAMP NOT NULL,
    POSTCODE NUMBER(5,0) NOT NULL,
    FOREIGN KEY (POSTCODE) REFERENCES CITY(POSTCODE)
);

CREATE TABLE SECTION(
    SECT_ID CHAR(5) PRIMARY KEY,
    SECT_NAME VARCHAR2(20) NOT NULL,
    SECT_FLOOR NUMBER(2,0) NOT NULL,
    SECT_DATE_CHECK DATE NOT NULL,
    WHS_ID CHAR(5) NOT NULL,
    FOREIGN KEY (WHS_ID) REFERENCES WAREHOUSE(WHS_ID)
);

CREATE TABLE EMPLOYEE(
    EMP_ID CHAR(5) PRIMARY KEY,
    EMP_PW VARCHAR2(12) NOT NULL,
    EMP_TIN VARCHAR(13) NOT NULL,
    EMP_IC CHAR(14) NOT NULL,
    EMP_FNAME VARCHAR2(20) NOT NULL,
    EMP_LNAME VARCHAR2(20) NOT NULL,
    EMP_ROLE VARCHAR2(20) NOT NULL,
    EMP_TITLE VARCHAR2(10) NOT NULL,
    EMP_BDATE DATE NOT NULL,
    EMP_PHONE VARCHAR2(13) NOT NULL,
    EMP_EMAIL VARCHAR2(20) NOT NULL,
    WHS_ID CHAR(5) NOT NULL,
    FOREIGN KEY (WHS_ID) REFERENCES WAREHOUSE(WHS_ID)
);


CREATE TABLE PRODUCT_INVENTORY(
    --COMPOSITE PRIMARY KEY REFERENCES TWO TABLES
    PROD_ID CHAR(6) NOT NULL,
    SECT_ID CHAR(6) NOT NULL,
    QTY NUMBER(10,0) NOT NULL
);

CREATE TABLE PRODUCT(
    PROD_ID CHAR(6) PRIMARY KEY,
    PROD_NAME VARCHAR2(20) NOT NULL,
    PROD_DESC VARCHAR2(100) NOT NULL,
    PROD_UOM VARCHAR2(8) NOT NULL,
    PROD_UNIT_PRICE NUMBER(8,2) NOT NULL
);

ALTER TABLE PRODUCT_INVENTORY
    ADD CONSTRAINT PRO_INV_COM_PK
    PRIMARY KEY(PROD_ID, SECT_ID);
    
ALTER TABLE PRODUCT_INVENTORY
    ADD CONSTRAINT PRO_INV_FK
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT;
    
ALTER TABLE PRODUCT_INVENTORY
    ADD CONSTRAINT SECT_ID_FK
    FOREIGN KEY (SECT_ID) REFERENCES SECTION;

DESCRIBE PRODUCT_INVENTORY;
