DELETE FROM FEEDBACKS;

INSERT INTO FEEDBACKS (FDB_RATE, FDB_DESC, FDB_DATE, ORD_ID) VALUES (5,'Excellent service, quick delivery!', TO_DATE('2025-01-21', 'YYYY-MM-DD'),'A0000001');
INSERT INTO FEEDBACKS (FDB_RATE, FDB_DESC, FDB_DATE, ORD_ID) VALUES (4,'On-time delivery but packaging could be better.', TO_DATE('2025-01-23', 'YYYY-MM-DD'),'A0000002');
INSERT INTO FEEDBACKS (FDB_RATE, FDB_DESC, FDB_DATE, ORD_ID) VALUES (3,'Delivery was late, but overall okay.', TO_DATE('2025-01-24', 'YYYY-MM-DD'),'A0000003');
INSERT INTO FEEDBACKS (FDB_RATE, FDB_DESC, FDB_DATE, ORD_ID) VALUES (4,'Good service but driver was late.', TO_DATE('2025-01-26', 'YYYY-MM-DD'),'A0000004');
INSERT INTO FEEDBACKS (FDB_RATE, FDB_DESC, FDB_DATE, ORD_ID) VALUES (5,'Perfect delivery, very professional.', TO_DATE('2025-01-28', 'YYYY-MM-DD'),'A0000005');