DELETE FROM RECYCLE_TRANSACTION;

INSERT INTO RECYCLE_TRANSACTION (RTRANS_AMOUNT, RTRANS_PAY_METHOD, RTRANS_DATE, RORD_ID) VALUES (500,'EWALLET', TO_DATE('2025-01-16', 'YYYY-MM-DD'),'RO00001');
INSERT INTO RECYCLE_TRANSACTION (RTRANS_AMOUNT, RTRANS_PAY_METHOD, RTRANS_DATE, RORD_ID) VALUES (300,'CARD', TO_DATE('2025-01-18', 'YYYY-MM-DD'),'RO00002');
INSERT INTO RECYCLE_TRANSACTION (RTRANS_AMOUNT, RTRANS_PAY_METHOD, RTRANS_DATE, RORD_ID) VALUES (1000,'CARD', TO_DATE('2025-01-20', 'YYYY-MM-DD'),'RO00003');
INSERT INTO RECYCLE_TRANSACTION (RTRANS_AMOUNT, RTRANS_PAY_METHOD, RTRANS_DATE, RORD_ID) VALUES (700,'CASH', TO_DATE('2025-01-22', 'YYYY-MM-DD'),'RO00004');
INSERT INTO RECYCLE_TRANSACTION (RTRANS_AMOUNT, RTRANS_PAY_METHOD, RTRANS_DATE, RORD_ID) VALUES (400,'CASH', TO_DATE('2025-01-24', 'YYYY-MM-DD'),'RO00005');