DELETE FROM SECTION;

INSERT INTO SECTION (SECT_NAME, SECT_FLOOR, SECT_DATE_CHECK, WHS_ID) VALUES ('Ready-Mix Concrete',1,TO_DATE('2025-09-01', 'YYYY-MM-DD'),'W0001');
INSERT INTO SECTION (SECT_NAME, SECT_FLOOR, SECT_DATE_CHECK, WHS_ID) VALUES ('Precast Concrete',2,TO_DATE('2025-09-02', 'YYYY-MM-DD'),'W0001');
INSERT INTO SECTION (SECT_NAME, SECT_FLOOR, SECT_DATE_CHECK, WHS_ID) VALUES ('Clay Bricks',1,TO_DATE('2025-09-03', 'YYYY-MM-DD'),'W0002');
INSERT INTO SECTION (SECT_NAME, SECT_FLOOR, SECT_DATE_CHECK, WHS_ID) VALUES ('Fly Ash Bricks',2,TO_DATE('2025-09-04', 'YYYY-MM-DD'),'W0002');
INSERT INTO SECTION (SECT_NAME, SECT_FLOOR, SECT_DATE_CHECK, WHS_ID) VALUES ('Structural Steel',1,TO_DATE('2025-09-05', 'YYYY-MM-DD'),'W0003');
INSERT INTO SECTION (SECT_NAME, SECT_FLOOR, SECT_DATE_CHECK, WHS_ID) VALUES ('Reinforced Steel Bars',2,TO_DATE('2025-09-06', 'YYYY-MM-DD'),'W0003');
INSERT INTO SECTION (SECT_NAME, SECT_FLOOR, SECT_DATE_CHECK, WHS_ID) VALUES ('Thermal Insulation',1,TO_DATE('2025-09-07', 'YYYY-MM-DD'),'W0004');
INSERT INTO SECTION (SECT_NAME, SECT_FLOOR, SECT_DATE_CHECK, WHS_ID) VALUES ('Roofing Tiles',2,TO_DATE('2025-09-08', 'YYYY-MM-DD'),'W0005');