DELETE FROM SHIPPING_DESTINATION;

INSERT INTO SHIPPING_DESTINATION (SHIPD_NAME, SHIPD_ADDR, COM_ID, POSTCODE) VALUES ('Sunway Construction Site','123 Jalan Tropicana, Petaling Jaya, Selangor','C0001',50000);
INSERT INTO SHIPPING_DESTINATION (SHIPD_NAME, SHIPD_ADDR, COM_ID, POSTCODE) VALUES ('Ecohill Development Site','45 Jalan Semenyih, Semenyih, Selangor','C0002',10300);
INSERT INTO SHIPPING_DESTINATION (SHIPD_NAME, SHIPD_ADDR, COM_ID, POSTCODE) VALUES ('The Light City Project','789 Persiaran Bayan Indah, Bayan Lepas, Penang','C0003',80000);
INSERT INTO SHIPPING_DESTINATION (SHIPD_NAME, SHIPD_ADDR, COM_ID, POSTCODE) VALUES ('Permas Heights Development','12 Jalan Permas Jaya, Johor Bahru, Johor','C0004',40100);
INSERT INTO SHIPPING_DESTINATION (SHIPD_NAME, SHIPD_ADDR, COM_ID, POSTCODE) VALUES ('East Coast Highway Extension','345 Jalan Kuantan-Kemaman, Kuantan, Pahan','C0005',11900);